"""add pessoa_endereco

Revision ID: 390fe8762740
Revises: 2fba02021094
Create Date: 2023-04-24 21:32:13.600773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390fe8762740'
down_revision = '2fba02021094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_column('senha')

    # ### end Alembic commands ###
